### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by acoquoin** [steevanb/php-url-test#9]
Hi my man !

I need a support for HTTPS.
I tried to ignore the SSL verification, but i can't (error: SSL connect error)

Could you implement it ?

Thanks !

**Comment by steevanb** [comment]
I will try to do something, found this tuto : http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/

**Comment by acoquoin** [comment]
It's work, you just need to add 
```php
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false
```
on UrlTest.php (line 243)

**Comment by acoquoin** [comment]
See: #10

**Comment by acoquoin** [comment]
up ?

**Comment by phpbenchmarks** [comment]
It's not a proper way to do it :)

When we don't have HTTPS, this curl options should not be defined.
Maybe we want to test our certificat.

So i will add configurations for it. Try to do it next week :)

**Comment by acoquoin** [comment]
Sorry next week it to long for us,  we we'll fork it, thank anyway :)

**Comment by phpbenchmarks** [comment]
I will work on it tomorrow, as i said, but as you want ;)
